name: Sunland
main: net.spence.minecraft.sunland.Sunland
version: 1.0

commands:
   basic:
      description: This is a demo command.
      usage: /basic
   maze:
      description: Generates a maze for the player
      usage: /maze
   mazeclear:
      description: Clears out a maze that was already built
      usage: /mazeclear
   skeleton:
      description: Summon a skeleton in front of you.
      usage: /skeleton
      