name: Sunland
main: net.spence.minecraft.sunland.Sunland
version: 1.0

commands:
   basic:
      description: This is a demo command.
      usage: /basic
   maze:
      description: Generates a maze for the player
      usage: /maze
   shop:
      description: Configure a shop
      usage: /shop
   skeleton:
      description: Summon a skeleton in front of you.
      usage: /skeleton
   coins:
      description: Create coins for use in the shops.
      usage: /coins <amount>
      